### ISSUE TITLE
Cloudflare remote error: tls: handshake failure

### ISSUE THREAD

**Issue by webchi** [yandex/pandora#130]
Hi. Get the issue with trying to load testing website behind the Cloudflare proxy. 
Config file:
```yml
pools:
  - id: HTTP pool                    # pool name (for your choice)
    gun:
      type: http
      target: target.site.com:443
      ssl: true
```
Error:
```
WARN	phttp/base.go:116	Request fail	{"pool": "HTTP pool", "instance": 7, "error": "remote error: tls: handshake failure"}
github.com/yandex/pandora/components/phttp.(*BaseGun).Shoot
	/home/icha1/Downloads/pandora/components/phttp/base.go:116
github.com/yandex/pandora/components/phttp.(*gunWrapper).Shoot
	/home/icha1/Downloads/pandora/components/phttp/core.go:43
github.com/yandex/pandora/core/engine.(*instance).shoot
	/home/icha1/Downloads/pandora/core/engine/instance.go:99
github.com/yandex/pandora/core/engine.(*instance).Run
	/home/icha1/Downloads/pandora/core/engine/instance.go:69
github.com/yandex/pandora/core/engine.runNewInstance
	/home/icha1/Downloads/pandora/core/engine/engine.go:407
github.com/yandex/pandora/core/engine.(*instancePool).startInstances.func2
	/home/icha1/Downloads/pandora/core/engine/engine.go:366
```
With another site (not behind cloudflare) everything work fine.
