### ISSUE TITLE
If gun has slow Close method, main function could exit before closing complete.

### ISSUE THREAD

**Issue by rapthead** [yandex/pandora#150]
Bug can be reproduced on single instance shooting.

Config:
```
pools:
  - id: example pool
    startup:
      type: once
      times: 1
  ...
```

Gun:
```
...
func (g *Gun) Close() error {
	fmt.Printf("Close start! %d\n", g.GunDeps.InstanceID) // Called
	time.Sleep(time.Second)
	fmt.Printf("Close done! %d\n", g.GunDeps.InstanceID) // Not called
	return nil
}
...
```
