### ISSUE TITLE
Out of ammo state is incorrect

### ISSUE THREAD

**Issue by rapthead** [yandex/pandora#151]
Engine think that provider is out of ammo when Run method is done but provider could have more ammo in buffered channel. That ammo can be Acquired.

Config to reproduce
```
pools:
  - id: HTTP pool
    ammo:
      type: uri
      limit: 20
      passes: 1
      headers:
        - "[Host: example.org]"
      file: ./ammo.uri
    gun:
      target: 'example.org:80'
      type: http
    rps-per-instance: true
    rps:
      - type: once
        times: 1
    startup:
      type: composite
      nested:
        - type: once
          times: 1
        - type: step # will never start because of false positive out of ammo
          from: 0
          to: 10
          step: 1
          duration: 5s
    result:
      type: phout
      destination: phout.log
log:
  level: debug
```
