### ISSUE TITLE
Issues with using http/scenario gun

### ISSUE THREAD

**Issue by scrabblett** [yandex/pandora#175]
Hi!
Encountered a problem when trying to use http/scenario gun.

The problem occurs when using Pandora with Yandex Tank. (if use Pandora only - all good)

My load.yaml
```
phantom:
  enabled: false
pandora:
  package: yandextank.plugins.Pandora
  enabled: true
  pandora_cmd: pandora # Pandora executable path
  config_file: config/pandora_config.yaml # Pandora config path
overload:
  enabled: true
  token_file: config/token.txt
  job_name: test
  job_dsc: test description
```

My pandora_config.yaml looks like (like in documentation):
```
pools:
  - id: HTTP pool                    
    gun:
      type: http/scenario
      target: api:8080

    ammo:
      type: http/scenario
      file: ./ammos/ammo.uri
```

but i`m getting error
```
2023-11-20T10:43:48.826Z	INFO	cli/cli.go:217	Reading config	{"file": "/app/logs/2023-11-20_10-43-40.929746/pandora_config_22gdez9d.yaml"}
2023-11-20T10:43:48.852Z	FATAL	cli/cli.go:226	Config decode failed	
{"error": "2 error(s) decoding:\n\n* error decoding 'pools[0].ammo': no plugins of type core.Provider has been 
registered for name http/scenario\n* error decoding 'pools[0].gun': no plugins of type core.Gun has been registered 
for name http/scenario"}
github.com/yandex/pandora/cli.readConfig
	/home/ligreen/github/pandora/cli/cli.go:226
github.com/yandex/pandora/cli.Run
	/home/ligreen/github/pandora/cli/cli.go:114
main.main
	/home/ligreen/github/pandora/main.go:27
runtime.main
	/usr/local/go/src/runtime/proc.go:255
error stacktrace:
github.com/yandex/pandora/core/config.Decode
	/home/ligreen/github/pandora/core/config/config.go:22
github.com/yandex/pandora/core/config.DecodeAndValidate
	/home/ligreen/github/pandora/core/config/config.go:26
github.com/yandex/pandora/cli.readConfig
	/home/ligreen/github/pandora/cli/cli.go:224
github.com/yandex/pandora/cli.Run
	/home/ligreen/github/pandora/cli/cli.go:114
main.main
	/home/ligreen/github/pandora/main.go:27
runtime.main
	/usr/local/go/src/runtime/proc.go:255
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1581
```
