### ISSUE TITLE
Plugin type defaults

### ISSUE THREAD

**Issue by skipor** [yandex/pandora#39]
Every plugin implementation can have it's own defaults. But user still needed to set 'type' field for every plugin. 
I propose to add default `type`s for every plugin.

**Comment by skipor** [comment]
I think, it's possible do more magic things! Maybe auto deduce plugin type? 
Iterate over all plugins and check if data "suitable" for this plugin config type.
"suitable" may mean, decoded without errors (do not create plugin, just decode config without validation), or check, that data keys is subset of config keys (may be harder).
If no plugin type suitable - error. If more than one plugin type suitable - error.


```yaml
rps:
   composite:
      - {from: 10, to: 50, duration: 3m}
      - {ops: 50, duration: 5m}
      - {once: 100}
      - {from: 50, to: 10, duration: 2m}

```
