### ISSUE TITLE
netsample binary Aggregator

### ISSUE THREAD

**Issue by skipor** [yandex/pandora#42]
First line: json metadata. Format like:
``` yaml
format: binary
date: 20-03-2017 20:17:53.122
type: response_stat
columns:
  - name: ts
    type: float64
  - name: urt
    type: int64
config: 
   pools:
     - id: 
     ....
```

Than print fields as is in big endian. One sample per line.
