### ISSUE TITLE
Error in console in the end of a test

### ISSUE THREAD

**Issue by direvius** [yandex/pandora#46]
```
Error waiting utils promises: 1 error(s) occurred:

* context canceled2017/06/23 21:11:00 Done
```

Config:
```
pools:
  - id: HTTP pool                    # Pool name
    gun:
      type: http                     # Gun type
      target: [my-host-here]:80  # Gun target
    ammo:
      type: uri                      # Ammo format
      file: ./ammo.uri               # Ammo File
    result:
      type: phout                    # Report format (phout is for Yandex.Tank)
      destination: ./http_phout.log  # Report file name
    rps:                             # RPS Schedule
      type: periodic                 # tick periodically
      batch: 1                       # in batches of two ticks
      max: 300                         # three batches total
      period: 0.1s                     # one batch each second
    startup:                         # Startup Schedule
      type: periodic                 # start Instances periodically
      batch: 1                       # one Instance at a time
      max: 5                         # five Instances total
      period: 0.5s                   # every 0.5 seconds
```

Ammo:
```
/
```
